### ISSUE TITLE
DownloadFromSerial.ino と通信するPCソフト

### ISSUE THREAD

**Issue by matsujirushi** [ciniml/ExtFlashLoader#1]
PCから、外部Flashでデータを書き込みたいのですが、DownloadFromSerial.ino と通信するPCソフトは公開されていますか？
https://github.com/ciniml/ExtFlashLoader/blob/master/examples/DownloadFromSerial/DownloadFromSerial.ino

**Comment by ciniml** [comment]
返事が遅くなってすみません。
`extflash.py` がそうなんですけど、現状argparseとか入れてないのでいろいろコード上にべた書きなのです。
デバイス名と書き込むファイル名がべた書きなので、そこを書き換えていただければとりあえず使えるとは思います。

https://github.com/ciniml/ExtFlashLoader/blob/master/extflash.py

**Comment by matsujirushi** [comment]
`extflash.py`気づきませんでした、、、。
ありがとうございます！
